name: Release Preview

run-name: Preview â€¢ ${{ github.ref_name }} â€¢ ${{ github.event.head_commit.message }}

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9]*"

permissions:
  contents: read
  actions: read
  checks: write
  packages: write

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›’ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ·ï¸ Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - name: âš™ï¸ Setup dotnet 8.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: ğŸ§¹ Clean
        run: dotnet clean -c Release && dotnet nuget locals all --clear

      - name: ğŸ—ï¸ Restore dependencies
        run: dotnet restore

      - name: ğŸ› ï¸ Build solution
        run: dotnet build --no-restore -c:Release -p:SourceRevisionId=${VERSION} -p:Version=${VERSION}

      - name: ğŸ“¦ Push packages to NuGet
        run: dotnet nuget push **/Cabazure.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_KEY }} --skip-duplicate --no-symbols